# A re-usable configuration of a Zwavejs2Mqtt container as a service.  If using this
# configuration in this directory from a git checkout, you may place custom
# modifications in `./docker-compose.override.yml` instead of un-commenting lines here
# to keep the `$ git status` clean.  Where `${...}` variable substitution is used, you
# may put values in a `./.env` file instead.  See `./docker-compose.override.yml.in` and
# `./.env.in` for examples.
services:

  zwave-js-ui:
    container_name: 'zwave-js-ui'
    image: 'zwavejs/zwave-js-ui:latest'
    restart: 'always'
    tty: true
    stop_signal: 'SIGINT'
    environment:
      SESSION_SECRET: '${SESSION_SECRET:?SESSION_SECRET must be defined}'
      # Add your timezone to `./.env` if you want logs time and dates to match your
      # timezone instead of UTC.  Available at:
      #     https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: '${TZ:-Etc/UTC}'
    networks:
      - 'zwave'
    devices:
      # Add your USB device path to `./.env`.  Do not use /dev/ttyUSBX serial devices,
      # as those mappings can change over time.  Instead, use the /dev/serial/by-id/X
      # serial device for your Z-Wave stick.
      - '${ZWAVEJS_DEV:?ZWAVEJS_DEV must be defined}:/dev/zwave'
    # Add a volume definition to `./.env` so that data persists across containers, which
    # should be ephemeral and not used to store data.
    volumes:
      - '${ZWAVEJS_VOLUME:?ZWAVEJS_VOLUME must be defined}:/usr/src/app/store/'
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: 'zwave-config'
